"""empty message

Revision ID: 04058d761bc2
Revises: ff056457698f
Create Date: 2019-10-20 13:11:22.078520

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04058d761bc2'
down_revision = 'ff056457698f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todos', 'list_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todos', 'list_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
